### ISSUE TITLE
Works great - a couple of suggestions

### ISSUE THREAD

**Issue by dushyantahuja** [jneilliii/OctoPrint-TasmotaMQTT#1]
I had to change the full topic to %topic%/%prefix%/ from the default (%prefix%/%topic%/) for it to work. Might make sense to change this in the code so that the default works.

Can you also enable the auto-connect and disconnect (similar to the OctoPrint-Tasmota plugin).
Thanks.

**Comment by jneilliii** [comment]
There's a separate branch I've been working on to incorporate multiple relays and all the other options in this repository. Logic doesn't work the same if you use that full topic pattern, and I don't remember changing that on my plug when I configured it.

**Comment by jneilliii** [comment]
Here is the working branch.  As it stands now, I just have the ui configured for adding the multiple relays.  From what I'm seeing on the Tasmota wiki it looks like your fulltopic template was the standard up to version 5.0.5, and has been replaced with the one I was using to program mine with the elimination of tasmota in front of it https://github.com/arendst/Sonoff-Tasmota/wiki/MQTT-Features#mqtt-topic-definition.

https://github.com/jneilliii/OctoPrint-TasmotaMQTT/tree/multi-mqtt-check

**Comment by jneilliii** [comment]
I've incorporate the initial framework for acting on the settings.  The only thing left is to handle GCODE processing and adjust the code accordingly.  I am having a similar issue that you were having with the web based version where the icon isn't updating for the first relay (I'm testing with my plug set as 4CH model) but the other ones are working fine.  I won't be able to debug that one until I get back home from vacation though.

**Comment by dushyantahuja** [comment]
That branch works perfectly. Had to blank out the index for the Sonoff Basic. But works great.
Thanks a lot.

**Comment by jneilliii** [comment]
Cool.  Once I get all the other changes finished for gcode processing I'll iterate a final release to the master branch. Please do let me know if you run into any problems.

**Comment by jneilliii** [comment]
Just released the latest changes, including all the features enabled.  Any feedback would be great prior to me releasing to the plugin repository if you don't mind.

**Comment by dushyantahuja** [comment]
Works great now thanks. Still, need to check the Gcode. But otherwise great.
