### ISSUE TITLE
No Ip On Setup Tab After Install

### ISSUE THREAD

**Issue by Paulf007** [jneilliii/OctoPrint-TasmotaMQTT#14]
I installed the plugin after I did a complete net Octoprint setup but there is no Ip box (Where I can add the MQTT server / sonoff's ip adress) Is there something else I am missing? The previous time it all worked well.
![2018-08-19_184223](https://user-images.githubusercontent.com/24200183/44310994-14193c00-a3e0-11e8-88ec-d783e4a57151.png)

**Comment by Paulf007** [comment]
Ok , I should have read the info first but there still seems to be a problem , 
 MQTT plugin should be installed first but then wen you send the switch command it publishes to the correct topic , in my case 3d_printer/cmnd/POWER, but there is no payload. I would assume that it should be TOGGLE , currently it is:  ""

**Comment by jneilliii** [comment]
Does the full topic setting on the main section match your tasmota device pattern?

**Comment by Paulf007** [comment]
Ok if have spent a bit more time on it and you need to change the topic template 
%prefix%/%topic%/
This seems to do the trick
