### ISSUE TITLE
Power on and off not working

### ISSUE THREAD

**Issue by MathijsG** [jneilliii/OctoPrint-TasmotaMQTT#15]
The GCODE power off and on function is not working. If I manually give the command

M81 $SONOFFIP 1

it doesn't do anything.

And I'm somewhat confused, you have this Octoprint-TasmotaMQTT plugin, but you also have Octoprint-Tasmota.

Can you elaborate on the differences or is one of these the successor of this add-on or something?

**Comment by jneilliii** [comment]
You have to have your relay added in the settings and gcode trigger enabled. The difference between the two is that one uses MQTT and the other just uses web communication for the people that don't want to set up a mqtt server.

**Comment by MathijsG** [comment]
I have added a number 1 to it:

![image](https://user-images.githubusercontent.com/529552/46734799-901f5a00-cc94-11e8-9527-0b500e329704.png)

And using this:

![image](https://user-images.githubusercontent.com/529552/46734817-9d3c4900-cc94-11e8-8c3c-5c9b48e9518f.png)


Doesn't do anything.

I tried the other Tasmota and that does work, but I like the MQTT way.

How can I debug further?

**Comment by MathijsG** [comment]
I removed the '1 ' again in the Relay input

But it now only can shutdown the switch, but it doesn't detect that it's off. Home-assistant and Domoticz are working perfectly with it. How can I help?

**Comment by jneilliii** [comment]
Does your full topic on the tasmota match the full topic configured in the plugin's general settings?

**Comment by MathijsG** [comment]
![image](https://user-images.githubusercontent.com/529552/46742682-da5e0680-cca7-11e8-8da1-f14ad97e53af.png)

![image](https://user-images.githubusercontent.com/529552/46742908-4476ab80-cca8-11e8-8be7-645f1a4c6c65.png)

Flashed latest tasmota on a sonoff S20 everything stock.

Path looks the same.

Somehow it CAN turn the printer off but it doesn't get perceived as off by your plugin. So the command always will be an OFF command, With the other plugin of you it changed in to a red or green state.

**Comment by jneilliii** [comment]
If you flashed a newer tasmota you need to include 1 in the relay field for their updated SetOption26, if it's enabled.

**Comment by MathijsG** [comment]
Doesn't make any difference unfortunately. It never detects that it has been shutdown. What topics do you use to read it's state? Maybe i'll dive into the code.

**Comment by jneilliii** [comment]
https://github.com/jneilliii/OctoPrint-TasmotaMQTT/blob/fdc4d4c02b51822504702308f1749a1d6fe547c5/octoprint_tasmota_mqtt/__init__.py#L46

**Comment by MathijsG** [comment]
Hmm, the stock topics of Tasmota are:

cmnd/sonoff/POWER
tele/sonoff/LWT

**Comment by MathijsG** [comment]
Yeah ofcourse :).

Tried everything :(.

Is it supposed to work in the terminal of octoprint?

The other plugin of you did work with M81 <IP>

**Comment by jneilliii** [comment]
It should. I'll verify later when I'm able to.

**Comment by MathijsG** [comment]
Okay, no hurry it isn't that big of a deal, but would be handy in the future to have the printer shutdown itself, instead of still having the fan and display turned on when I come back home.

**Comment by jneilliii** [comment]
So I just tried on my pi and the gcode triggers are working perfectly for me.  One thing I noticed though was that some of my other plugins are throwing errors with those triggers so not sure if that is causing the trouble for you maybe.  I'll have to dig deeper into that for those.  If you do have one of my other gcode triggered ones let me know and I can check those first.

Commands should be formatted based on the following format:

```
On
M80 topic 1 or M80 topic

Off
M81 topic 1 or M81 topic
```

So with your settings in the screenshot earlier the command would be `M81 sonoff` to power off your device.


Which version firmware are you running on your tasmota?  If you go to the web interface > console what is the result of sending `SetOption26`?

**Comment by jneilliii** [comment]
> By the way: Can you drop me your paypal address in private? You get considerably less money when I donate via that button instead of transferring you money.

I don't think git has a PM mechanism, are you registered on the [Community Forum](https://discourse.octoprint.org/)?

**Comment by MathijsG** [comment]
Hey man, I'm sorry, maybe it wasn't written in the instruction but I didn't know of that syntax, I thought because with mqtt it doesn't need an IP (like it does with the other tasmota plugin) the syntax should be just M81. 'M81 sonoff' is working perfectly :)

Can you email me on mathijs.groothuis@gmail.com with the address?
