### ISSUE TITLE
Plugin can't detect power state of tasmota

### ISSUE THREAD

**Issue by johny-mnemonic** [jneilliii/OctoPrint-TasmotaMQTT#18]
Could you please shed some light on how exactly do you detect power state of the Tasmota?

I am running Sonoff basic with Tasmota 5.12 and while I tried setting both "%topic%/%prefix%/" and "%prefix%/%topic%/" in my Tasmota and in the plugin, it can't detect the power state of it.

Now it says my Tasmota is ON and it is sending "OFF" command no matter in which state the Tasmota currently is. 
Is there anything I have to configure in Tasmota to make it work with this plugin?
Using MQTT.fx I can see that the device correctly reports it's state on stat/%topic%/POWER in plain text and stat/%topic%/RESULT in json.

**Comment by jneilliii** [comment]
Sounds like maybe the issues is the SetOption26 (I think that's it) in Tasmota. If you add a number 1 in the relay field does it work?
