### ISSUE TITLE
Can't send M80 command while printer is disconnected

### ISSUE THREAD

**Issue by kulfuerst** [jneilliii/OctoPrint-TasmotaMQTT#19]
Hi jneilliii,
firstly, I absolutely love the plug in! Thank you very much for suppling it and looking after it :)
Now I am very new to Octoprint and am still navigating all the possibilities so I feel like an idiot for asking. How do I send the M80 IPAddress Command to Octoprint, when the Command line is disabled due to a disconnected printer? When I turn the printer off by clicking the lightning bolt or sending the M81 command, Octoprint changes the monitoring state from "Operational" to "Offline" and greys out the command line. I also cannot send commands in my OctoRemote App on my phone when the printer is disconnected. I'm sure this is a user error, but I'm afraid I have a really hard time getting to the bottom of this. Thank you very much for your help and keep up the great work :)

**Comment by jneilliii** [comment]
Yeah, the M80 command was one that I struggled over adding for this specific reason. If your printer powers off and you aren't connected to terminal you obviously can't power on the printer with gcode. It's really for people who aren't using it to control power to their printer but to control lights or fans, etc. If you're using it to control power to the printer then you would have to use the button in the navbar to lower back on your printer. It's like a toggle switch.

**Comment by kulfuerst** [comment]
Thank you very much for your reply. Would it be possible to use system commands to toggle the on switch? I tried finding out where this switch is located that triggers the activation of the wemo but I wasn’t succesful, could you maybe tell me the path?
Best wishes

Von: jneilliii
Gesendet: Montag, 28. Januar 2019 02:14
An: jneilliii/OctoPrint-TasmotaMQTT
Cc: kulfuerst; Author
Betreff: Re: [jneilliii/OctoPrint-TasmotaMQTT] Can't send M80 command whileprinter is disconnected (#19)

Yeah, the M80 command was one that I struggled over adding for this specific reason. If your printer powers off and you aren't connected to terminal you obviously can't power on the printer with gcode. It's really for people who aren't using it to control power to their printer but to control lights or fans, etc. If you're using it to control power to the printer then you would have to use the button in the navbar to lower back on your printer. It's like a toggle switch.

**Comment by jneilliii** [comment]
The button is the one at the top of the page with a lightning bolt symbol by default. Our will be red when the device is powered off, green if on. You press the same button. 

https://github.com/jneilliii/OctoPrint-TasmotaMQTT/blob/master/navbar.png
