### ISSUE TITLE
Request: possibility to cancel switch off

### ISSUE THREAD

**Issue by FrankX0** [jneilliii/OctoPrint-TasmotaMQTT#21]
Would it be possible to cancel the switching off when the GCODE triggered off delay is enabled?
I use this feature to switch off my printer after the print has finished when I am not around.
But when I am near my printer, I would like to be able to cancel the switching off.
So could an interface be added to be able to cancel the switching off?
Maybe through a pop-up, or by flashing the icon during the off delay and clicking it to cancel?

**Comment by jneilliii** [comment]
I've integrated an abort timer in my other power related plugins and will probably be merging those changes into this plugin as well.  Stand by for future updates.
