### ISSUE TITLE
Improve documentation alittle

### ISSUE THREAD

**Issue by CWempe** [jneilliii/OctoPrint-TasmotaMQTT#24]
I just installed this plugin and I think I will like it.

But I would like some more explanations for each setting.  
e.g. in a table in the README or with tool tips inside the website.

  * What do `Auto Connect` and `Auto Disconnect` mean?
  * What units are the Delays? (seconds I guess)

**Comment by beardedfool** [comment]
Just to help you might want to reference the other, similar, plugin for some of the answers

https://github.com/jneilliii/OctoPrint-Tasmota

**Comment by CWempe** [comment]
Thanks

**Comment by jneilliii** [comment]
Thanks to @torwag, the readme has been updated with better documentation.
