### ISSUE TITLE
Stat is not received for %topic%/%prefix%/

### ISSUE THREAD

**Issue by torwag** [jneilliii/OctoPrint-TasmotaMQTT#25]
Hi, 
I changed the topic to %topic%/%prefix%/ as this is the way I use it in all my set-ups. 
The sonoff (in my case a sonoff POW)  gets the "cmnd/Power ON" message. However, the symbol spins forever. As far as I can debug this, the plugin somehow misses the feedback from %topic%/stat/POWER. In the logfile I can see that frequently 

"octoprint.plugins.tasmota_mqtt - INFO - checking status of 3D_printer relay" get logged. Looking up in the code I found 
[line 119](https://github.com/jneilliii/OctoPrint-TasmotaMQTT/blob/1acd03116935dc596b7c7eb31882d5e5491d3967/octoprint_tasmota_mqtt/__init__.py#L119) get called. As far as I understand, this should trigger the stat message. However, it seems it never gets the stat update and therefore spins forever

**Comment by jneilliii** [comment]
Can you please enable debugging and post some logs for me.  Make sure to include a screenshot of your settings as well.  What version of tasmota firmware are you running? The POW is a single relay device, isn't it, did you enable that option?

**Comment by torwag** [comment]
I turned on debug for MQTT and Tasmota-MQTT
Lets see what we can find. 
Tasmota firmware is 6.6.0

I can see that the relay turns on and I can turn it off via another MQTT client. Thus, I think the Tasmota is ok. It seems that the feedback is somewhat not received.

What do you mean by 

> The POW is a single relay device, isn't it, did you enable that option?
Yes it is a single relay device. How can or should I enable that, other than leaving the relay field empty.

Having the topic and prefix in reverse order, it worked out correctly. Came to this point because I cannot use the M80 and M81 commands. 
What a joy if you try to fix a problem and create a new one.  ;)

**Comment by torwag** [comment]
OK close this.... I did a reboot after I noticed that the logging did not happen and I thought a fresh reboot might trigger the generation of the log-files.... well it also solved the problem with the MQTT toipic and prefix.
