### ISSUE TITLE
Autoconnect fails if already connected

### ISSUE THREAD

**Issue by torwag** [jneilliii/OctoPrint-TasmotaMQTT#27]
Not totally sure, but it seems the autoconnect function leads to an error if the printer is connected already. 
If I print something and connect to the printer before (otherwise one can not send a print-job). The print jobs starts (bed starts heating) but finally an octoprint issues an error that and the print is interrupted. In the terminal the following will be reported:
```

Changing monitoring state from "Printing" to "Offline"
Changing monitoring state from "Offline" to "Detecting serial port"
Serial port list: ['/dev/ttyUSB0']
Connecting to: /dev/ttyUSB0
Changing monitoring state from "Detecting serial port" to "Error: Connection error, see Terminal tab"
Unexpected error while connecting to serial port: None SerialException: '[Errno 11] Could not exclusively lock port /dev/ttyUSB0: [Errno 11] Resource temporarily unavailable' @ comm.py:_openSerial:2661 (hook default)
Connection closed, closing down monitor
```
If autoprint is switched off, it works correct. 
I believe we have a challenge here with how to the device get switched on. If switched on manually (pressing the icon) it makes sens to perform the autoconnect. However, if switched on via GCODE, the printer will be on already. I try to verfify this behaviour in the code and see if it really tries to issue a connection starting from GCODE.

**Comment by jneilliii** [comment]
The autoconnect option should probably check to see if the printer is already connected prior to trying to connect again...would need to add that check in [here](https://github.com/jneilliii/OctoPrint-TasmotaMQTT/blob/c64cc10740538b0114d7b3cdfb9e3ee464c5b6e9/octoprint_tasmota_mqtt/__init__.py#L141).

**Comment by torwag** [comment]
I checked and indeed the GCODE function start the same turn_on function to trigger the relay and if the flag for autoconnect is set this issues the command to auto connect. Not sure what is the best way to solve this. One could introduce a parameter for the turn_on method to indicate from where ist was started or write a new turn_on function, as it was done with the turn_off function.
A "smarter" way would be to check the status and if already connected, it would not try to connect.
If you tell me what you prefer, I can look into it.

**Comment by jneilliii** [comment]
I just pushed version 0.3.4 to a new branch.  Try installing the plugin using the url below in plugin manager and let me know if it works as I think it should. Haven't had a chance to test yet.

https://github.com/jneilliii/OctoPrint-TasmotaMQTT/archive/0.3.4.zip

**Comment by torwag** [comment]
Thanks for the quick fix. Now it seems to work correctly. 
If you consider 0.3.4 the next upcoming release you can mark this issue as fixed.
