### ISSUE TITLE
user/pass for the broker?

### ISSUE THREAD

**Issue by arhi** [jneilliii/OctoPrint-TasmotaMQTT#29]
cannot connect to broker without username and password :(
TLS support?

**Comment by jneilliii** [comment]
Pretty sure all those options are part of the MQTT plugin, not this one. This plugin utilizes the broker connection established by the other plugin.

**Comment by arhi** [comment]
it uses the other plugin? https://github.com/OctoPrint/OctoPrint-MQTT ? ... damn I am a complete idiot sorry :(

**Comment by jneilliii** [comment]
> I am a complete idiot sorry

You said it, not me...lol.  Yeah, the connection is managed by that plugin and this plugin just uses the same connection.

**Comment by arhi** [comment]
I set the "other" plugin fine and was testing nodered and this one was failing to run properly and I got totally sidetracked debugging a wrong thing .. speaking of not seeing the tree from the forrest .. all cool now .. the "autodiscovery" fr on the other hand, still think that's a good idea :)
