### ISSUE TITLE
Sonoff POW

### ISSUE THREAD

**Issue by sgoudelis** [jneilliii/OctoPrint-TasmotaMQTT#3]
Hello,

I am using a Sonoff POW with Tasmota installed. I cant get this work this with this sonoff. From your configuration suggestions, what should I use as a topic in the tasmota webui configuration ? For example: switchname/1/ or the actual string "%topic%/%prefix%/" ? Also if there some debug log I can view ? I know that the MQTT plugin works in my octopi because I can see the messages of starting and stopping a print, coming into Node-RED. 

Have you tried to use this plugin with a Sonoff POW ? Does it require any special config ? Relay, index or something else perhaps ?

**Comment by jneilliii** [comment]
In the sonoff device configure the full topic as %topic%/%prefix%/

Make sure the mqtt setting on the sonoff device are using the same server address as the mqtt plugin. 

Verify your running at least version 5.11 firmware on the sonoff. 

In the plugin settings the topic is the same as In the sonoff configuration (not full topic, just topic). Set tertiary to 1 and make sure single relay device option is checked.

**Comment by sgoudelis** [comment]
Thank you, upgrading did it for me.
