### ISSUE TITLE
How to configure ? sending incorrect payload

### ISSUE THREAD

**Issue by bakman2** [jneilliii/OctoPrint-TasmotaMQTT#31]
I was creating something in node-red and stumbled upon this plugin, it looks to be very useful, thanks! 

I am having some trouble configuring the topics.

Copying the "full topic" from my tasmota device doesn't work with the topic/prefix as my devices are organized per room, ie; `devices/kleine_kamer/mpmd` is my printer.

I configured it as:
![Screenshot 2019-12-04 at 16 33 36](https://user-images.githubusercontent.com/333960/70156485-4b365e00-16b4-11ea-8e9c-3d8a5a92a447.jpg)

Looking in node-red, the plugin sends `devices/kleine_kamer/mpmd/cmnd/POWER0` when I click the little power icon in the navbar:

![Screenshot 2019-12-04 at 16 33 44](https://user-images.githubusercontent.com/333960/70156652-92bcea00-16b4-11ea-9be0-5ba0dd2ec4e7.jpg)

This should be `devices/kleine_kamer/mpmd/cmnd/POWER 1` ?
(I assume that I can turn the printer on with the icon ?)

Also I was wondering how the control via g-code works - I cannot trigger a terminal command/print command as the printer is turned off; not connected.

**Comment by jneilliii** [comment]
Sending an empty payload is the plugin trying to receive the current power status.  Instead of using idx 0 try leaving that field blank or enabling the single relay device option, assuming you are using a single relay device.

**Comment by bakman2** [comment]
Thanks a lot for the quick response, it works. 

Next problem I am facing, the auto reconnect somehow does not want to play nice:
```
Changing monitoring state from "Operational" to "Offline"
Changing monitoring state from "Offline" to "Detecting serial port"
Serial port list: ['/dev/ttyACM0', '/dev/ttyACM1']
Trying /dev/ttyACM0
Changing monitoring state from "Detecting serial port" to "Error: Connection error, see Terminal tab"
Unexpected error while connecting to serial port: None IspError: ''Timeout'' @ comm.py:_openSerial:2661 (hook malyan_connection_fix)
```
I have 2 serial devices and it needs to pick `ttyACM0`, problem is, it is not detected automatically in the UI and I need to click the refresh icon first, after which I can connect. From node-red I can POST a `connect` to the API and it connects automatically. I see in [the code here](https://github.com/jneilliii/OctoPrint-TasmotaMQTT/blob/85389de67120202b7f80d5a35212e96494ca097a/octoprint_tasmota_mqtt/__init__.py#L142) that a system call is being made, these 2 seem to behave differently.

**Comment by jneilliii** [comment]
I've never had the issue you are describing. Have you tried extending the connect delay a bit to give the printer enough time to power up completely prior to the plugin sending the _printer.connect command. That is an internal command to OctoPrint and should behave the same as the API. You could try setting the port in the UI and checking the Save Settings option and press Connect. Then maybe the plugin will work as expected.

**Comment by bakman2** [comment]
There are 2 things at play here I think.

1) my printer has some serial issue for which there is a plugin available and I am using.
2) the internal command behaves differently from the API, as the API can connect, internal commands (also the web interface) cannot, until a refresh of the devices has been done.

I have [opened an issue](https://github.com/OctoPrint/OctoPrint-MalyanConnectionFix/issues/4) on the plugin for the serial, although it might be different problem (within octoprint itself)

**Comment by jneilliii** [comment]
Not really sure then.  Since you are using Node Red though you could handle the connection stuff using  an api call as a reaction to the power being turned on.

**Comment by bakman2** [comment]
Indeed, I am controlling more thing for the printer there, leds and stuff. I was planning to trigger the printer to turn on when octoprint receives a `octoPrint/event/FileAdded` event via mqtt. I will close this issue. Thanks for the quick service!
