### ISSUE TITLE
update to 0.3.6 wiped configured units

### ISSUE THREAD

**Issue by Henrik77** [jneilliii/OctoPrint-TasmotaMQTT#35]
Hi

Just updated to plugin version 0.3.6
I previously had 4 tasmota units configured - with various options enabled.
All 4 were gone/wiped when i updated !

If this was intentional is should probably be clearly warned before update of the plugin.

PS : the auto-off seems awesome  - testing right now ;-)

**Comment by jneilliii** [comment]
I apologize, that was not intentional and I made every effort to try avoiding it. This was probably due to the new topic format structure introduced by another contributor.

**Comment by jneilliii** [comment]
Updated release with warning about this.

**Comment by Henrik77** [comment]
No problem.  Great with the added warning - then people can note down/screenprint their setup before update.
