### ISSUE TITLE
GCODE ON/OFF commands don't support single relay

### ISSUE THREAD

**Issue by paran0ic** [jneilliii/OctoPrint-TasmotaMQTT#4]
Hello!

in line 168 (octoprint_tasmota_mqtt/__init__.py) condition:
`if cmd.startswith("M8") and cmd.count(" ") >= 2:`

not accept mqtt command for single relay:
`M81 sonoff-basic `

**Comment by jneilliii** [comment]
Add a 1 to the end of your gcode command.

**Comment by jneilliii** [comment]
My apologies, this is a bug.  I updated the logic on my other tasmota web based plugin not this one.  I'll review and post an update this weekend.
