### ISSUE TITLE
Shut-down clock triggered upon start-up 

### ISSUE THREAD

**Issue by SirGoodenough** [jneilliii/OctoPrint-TasmotaMQTT#42]
i use your addin here to shut down both the PI and the printer after heater cool and a delay.  Works awesome that way.
However, when I turn the switch back on (from external means as the pi is off) it starts up in the shut-off mode timer and (set to 3 minutes warning).  I have this set time to get the console open and cancel the shutdown before tasmotamqtt shuts the switch off again.  Can there be a setting, or is there a setting i am not understanding that recognizes that the PI has just powered up and the shutdown timer should be restarted at 0, not causing the software to be started up in shutdown mode?

**Comment by jneilliii** [comment]
Can you share screenshots of your settings so I can better understand how you have it configured?

**Comment by SirGoodenough** [comment]
![Screenshot from 2020-07-22 22-30-24](https://user-images.githubusercontent.com/47349533/88249792-2145a200-cc6b-11ea-91ab-6c368a456055.png)
![Screenshot from 2020-07-22 22-30-03](https://user-images.githubusercontent.com/47349533/88249793-21de3880-cc6b-11ea-9b01-38174ba2df86.png)

**Comment by SirGoodenough** [comment]
I think you can see it all.   I'm printing at the moment...

**Comment by SirGoodenough** [comment]
![Screenshot from 2020-07-23 19-22-57](https://user-images.githubusercontent.com/47349533/88350850-fb2b0b00-cd19-11ea-89c5-1134398a60a5.png)

This is the view on power-up.  If I don't get there in time and it shuts down the switch, It will then power up normally not triggered for shutdown.  Obviously timer reset....

**Comment by nanuit** [comment]
I have the same issue.
Every time i start my octopi the shutdown counter of the plugin starts and i had to set the timeout to a large enough value not to shutdown before i can open the octoprint software and cancel the shutdown.
Is there a configuration where the idle timer expired directly after octoprint start?

**Comment by jneilliii** [comment]
The only configuration is the idle timer being enabled. It starts as soon as octoprint starts, and gets reset when a print starts. In my mind the idle timer is similar to a screensaver or power saving in windows. It should be something that happens after a longer period of time.

**Comment by nanuit** [comment]
Is there a change to add a feature to start the idle timeout only after a print has finished..
I need the idle timeout only for this occasion, so that after a long print the printer is not running until i get to it.

As long as i have not startet a print i am working with the printer and there is no need to shut it down.

**Comment by jneilliii** [comment]
that's what the gcode triggers are for. you can enable that option, and relative delays, and then in your end gcode scripts of your slicer or within octoprint's gcode scripts settings you add the relevant gcode off commands.

**Comment by nanuit** [comment]
I have tried that, the M81 is sent to the printer but the plugin is not activating the tasmota device.

**Comment by nanuit** [comment]
or rather deactivating

**Comment by nanuit** [comment]
He who can read has the advantage. 
After sending the correct M81 command, it works

Thank you

**Comment by jneilliii** [comment]
I've implemented some better logic relative to starting up a pi that should help with this idle timeout. I've incorporated an uptime comparison so that is the uptime is shorter than the idle timeout length it will reset the timer. This should resolve this issue. If you'd like to try this out for me and verify copy/paste the URL below into Plugin Manager > Get More > ...from URL and click Install.

```
https://github.com/jneilliii/OctoPrint-TasmotaMQTT/archive/0.3.8rc3.zip
```

**Comment by nanuit** [comment]
> I've implemented some better logic relative to starting up a pi that should help with this idle timeout. I've incorporated an uptime comparison so that is the uptime is shorter than the idle timeout length it will reset the timer. This should resolve this issue. If you'd like to try this out for me and verify copy/paste the URL below into Plugin Manager > Get More > ...from URL and click Install.
> 
> ```
> https://github.com/jneilliii/OctoPrint-TasmotaMQTT/archive/0.3.8rc3.zip
> ```

with this version I do not get the countdown window directly after launching octoprint.
Thanks

**Comment by jneilliii** [comment]
And you have the options enabled for both the general idle timeout and off on idle in the relay's settings?

**Comment by nanuit** [comment]
> And you have the options enabled for both the general idle timeout and off on idle in the relay's settings?

yes, both are active

**Comment by jneilliii** [comment]
Weird, it's working here as expected. With the pi completely powered off when I power on the pi my relay is powered on, then 5 minutes after the pi connects to the printer the idle timer kicks in and prompts for 30 seconds with the abort option. Are you using the option for auto connecting to the printer?

**Comment by nanuit** [comment]
You misunderstood me. Now with the fix it works as it should. Without the fix the shutdown popup was shown and counted down immediately  after octoprint has started. Now it appears after the idle timeout. As it should.

**Comment by jneilliii** [comment]
Ok, perfect. So the next release will resolve this issue.
