### ISSUE TITLE
Turning on Relay(s) on file upload to OctoPrint server

### ISSUE THREAD

**Issue by plasota** [jneilliii/OctoPrint-TasmotaMQTT#47]
Hey @jneilliii, great job on this plugin, it works great! I have a simple Tasmota WiFi plug that I'm using to control power to my printer. With this configuration, the printer's control board is not powered, and therefore can't run the "turn on relay" Gcode (as far as I understand). I wanted to create a more streamlined workflow, where I can achieve this:

1. Upload a sliced file through Cura (via the OctoPrint plugin)
2. The relay is switched to "on" when the file is received on the OctoPrint server
3. OctoPrint waits according to the time set in TasmotaMQTT plugin, and then connects to the printer
4. The print is started with the AutotartPrint plugin.

This way, I don't have to interact with the OctoPrint UI at all - I just send the file to the OctoPrint queue, and everything else happens automatically.

I modified your plugin to allow powering on specific relays on a file upload event, and it works great for me. If you'd like, I can submit a PR to add this feature to your plugin. Let me know if you'd be interested in doing that!

**Comment by jneilliii** [comment]
Actually, you could do this from the Cura plugin side to automatically power on and start the print...the Cura plugin will actually see this plugin installed and allow you to pick the relay to power on before upload.

![image](https://user-images.githubusercontent.com/5249455/95789893-5c74d180-0cac-11eb-80bd-7493b0fc9354.png)

**Comment by plasota** [comment]
Oh cool, that's super easy! For some reason, those options are not available to me ("Select print job after uploading" is unchecked and greyed out, so I can't check it, and "Turn on printer with" is not there at all). I'm on Cura 4.7.1 and OctoPrint Cura plugin 3.5.17 like you, and OctoPrint 1.4.2. 

After tinkering for a bit, I updated the OctoPrint Cura plugin to a dev version, and now "Select print job after uploading" can be checked, but "Turn on printer with" is still not there.

**Comment by jneilliii** [comment]
That's odd, I have all the same versions of those. Maybe this MQTT version of the Tasmota plugin isn't supported by the Cura plugin. I thought it was though.

**Comment by jneilliii** [comment]
That's what it is...only the non MQTT version is supported....

https://github.com/fieldOfView/Cura-OctoPrintPlugin#plugins

**Comment by plasota** [comment]
Got it, that explains it. I'll switch over to the non MQTT version then. I guess you could add what I described as a work-around, but since there's a more integrated solution with an alternative option (the non MQTT plugin), that's not super necessary. I'll leave up to you whether you want to keep this issue open to keep track of the missing integration from the Cura-OctoPrintPlugin repo.

**Comment by jneilliii** [comment]
I will leave it open to add on upload, as that will also allow for the use of PrusaSlicer/SuperSlicer direct upload to OctoPrint. I've already done something similar in my TPLink plugin.

BTW if you have my Cura Thumbnails plugin installed when the Cura plugin detects it a thumbnail will get uploaded to your octoprint instance as well and can be shown in the file list...

**Comment by jneilliii** [comment]
I've added this to support the PrusaSlicer/SuperSlicer uploads in the commit above. If you want to test it out for any reason you can copy/paste the URL below into Plugin Manager > Get More > ...from URL and clicking Install.

```
https://github.com/jneilliii/OctoPrint-TasmotaMQTT/archive/0.3.8rc3.zip
```
