### ISSUE TITLE
Feature Request: configured MQTT topic

### ISSUE THREAD

**Issue by paran0ic** [jneilliii/OctoPrint-TasmotaMQTT#5]
MQTT topic is hardcoded as `%topic%/%prefix%/`

It is possible to add configuration setting to use custom topic? For example I use: `switches/%prefix%/%topic%/`. I changed it in local code, because my all other "SmartHome" solutions using this topic format.

**Comment by jneilliii** [comment]
This will require a good amount of updating to the code to get to work.  I will consider the change.

**Comment by hakan42** [comment]
To add my config, I have multiple sonoffs in the house, and the one for the printer has following topics:

tasmota/stat/sonoff-prusa/POWER

with "sonoff-prusa" being the name that I configured in the UI of your plugin.

**Comment by hakan42** [comment]
Works great now, thank you 👍
