### ISSUE TITLE
Not working - sending %fullTopic%/POWER with no arguments

### ISSUE THREAD

**Issue by Roo426** [jneilliii/OctoPrint-TasmotaMQTT#50]
I want to use OctoPrint-TasmotaMQTT to turn my printer on/off using a Shelley setup with MQTT. My MQTT sever is running and I see OctoPrint's messages (MQTT plugin installed). I started by installing OctoPrint-Tasmota and could not get it to work. It set up for MQTT. I then installed OctoPrint-TasmotaMQTT and managed to get it to work. So I uninstalled OctoPrint-Tasmota and then OctoPrint-TasmotaMQTT stopped working.

The icon-bolt stays orange, if I click it it starts spinning and never stops. I does send the correct topic "cmnd/mydevice/POWER" but with no "ON"/"OFF" arguments. So it almost works! 

If I send POWER/ON command manually via MQTT.fx The bolt Icon changes colors and now my Shelly does not react (it works via the tasmota web page) I think the problem came about when I ran OctoPrint-Tasmota and it gave me an error saying the tasmota "setoptionxxx" need to be changed so I did. Don't remember witch option it was, maybe 109? 

Anybody have the same issue?

**Comment by jneilliii** [comment]
Since you had the other plugin installed, you may need to disabe SetOption26 now to use this one. Go to the web interface of your Tasmota and run the command `SetOption26 off` and try again and see if that fixes it.

**Comment by Roo426** [comment]
Thanks for the quick reply…. 26 was off, mind you I even tried a different Shelly. Still doesn’t work. There’s just no argument fed from the plugin, just the topic, so I can see it being the my device. Any way of setting the “ON” / “OFF” commands to use in the plugin?  Sent from Mail for Windows 10 From: jneilliiiSent: January 25, 2021 21:57To: jneilliii/OctoPrint-TasmotaMQTTCc: Roo426; AuthorSubject: Re: [jneilliii/OctoPrint-TasmotaMQTT] Not working - sending %fullTopic%/POWER with no arguments (#50) Since you had the other plugin installed, you may need to disabe SetOption26 now to use this one. Go to the web interface of your Tasmota and run the command SetOption26 off and try again and see if that fixes it.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jneilliii** [comment]
The plugin sends the commands. I need you to enable debug logging and provide a log file.

**Comment by Roo426** [comment]
OK, I will do that tomorrow, I’m heading to bed. I know how to enable the logging, where do I find the file?

Rob

**Comment by jneilliii** [comment]
You'll find it in the logging section of OctoPrint. Please share your octoprint.log file and plugin_tasmotamqtt_debug.log. You'll have to drag them into a comment here on github though, attachments won't forward through via email.

**Comment by Roo426** [comment]
Hi, my OctoPi is pretty fresh so the files are not that big. I added the tasmota_debug also if you want to look at that but it’s not installed at the moment. 

I was also thinking of restarting my OctoPi image with the new one that just came out so maybe that would help.

My Shelly fullTopic is: cmnd/tasmota_55604C/
When I press the bolt icon I get these MQTT messages:

cmnd/tasmota_55604C/POWER.  With no payload
stat/tasmota_55604C/RESULT      {"POWER":"OFF”}
octoprint/plugin/tasmota.                echo:
stat/tasmota_55604C/POWER.     OFF
And multiple
octoprint/plugin/tasmota                 echo:

And then more opctoprint status & temp messages

**Comment by jneilliii** [comment]
again, you'll need to drag the logs into a message here, you cannot attach them to an email, they don't come through.

**Comment by Roo426** [comment]
[octoprint.log](https://github.com/jneilliii/OctoPrint-TasmotaMQTT/files/5874291/octoprint.log)
[plugin_tasmota_debug.log](https://github.com/jneilliii/OctoPrint-TasmotaMQTT/files/5874292/plugin_tasmota_debug.log)
[plugin_tasmota_mqtt_debug.log](https://github.com/jneilliii/OctoPrint-TasmotaMQTT/files/5874293/plugin_tasmota_mqtt_debug.log)

**Comment by jneilliii** [comment]
Thanks this is weird. I see this in the octoprint.log, which is probably the underlying cause.
```
2021-01-26 02:25:08,517 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin tasmota_mqtt
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/server/api/__init__.py", line 146, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/__init__.py", line 1890, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_tasmota_mqtt/__init__.py", line 377, in on_api_command
    self.mqtt_unsubscribe(self._on_mqtt_subscription,topic=self.generate_mqtt_full_topic(relay, "stat"))
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mqtt/__init__.py", line 398, in mqtt_unsubscribe
    self._mqtt.unsubscribe(*subbed_topics)
TypeError: unsubscribe() takes at most 3 arguments (28 given)
```
Could you please share screenshots of your settings for me? Again, I think you'll have to paste them here in a github comment.

**Comment by Roo426** [comment]
<img width="567" alt="Screen Shot 2021-01-26 at 11 41 50" src="https://user-images.githubusercontent.com/16093584/105868895-0adb2300-5fcd-11eb-8900-4e00b44710c3.png">
<img width="682" alt="Screen Shot 2021-01-26 at 11 42 11" src="https://user-images.githubusercontent.com/16093584/105868922-10d10400-5fcd-11eb-9363-424f23349981.png">
<img width="498" alt="Screen Shot 2021-01-26 at 11 45 59" src="https://user-images.githubusercontent.com/16093584/105868928-12023100-5fcd-11eb-9fde-c77c7eca751b.png">
<img width="486" alt="Screen Shot 2021-01-26 at 11 46 15" src="https://user-images.githubusercontent.com/16093584/105868932-129ac780-5fcd-11eb-9ee2-7df010b538e1.png">

**Comment by jneilliii** [comment]
ok, I think I see where the issue may be. Your topic and full topic in the plugin's settings should match what you have configured in Tasmota. 

![image](https://user-images.githubusercontent.com/5249455/105869373-2b9f7a80-5fc5-11eb-9038-a2653100bbe3.png)

**Comment by Roo426** [comment]
<img width="391" alt="Screen Shot 2021-01-26 at 12 03 24" src="https://user-images.githubusercontent.com/16093584/105870301-825d8200-5fce-11eb-90e8-3b4594090457.png">

**Comment by Roo426** [comment]
Bingo, your a genius, thanks for your help. It works now.

Your support is awesome. I will be sending you a donation for your work.

Rob
