### ISSUE TITLE
[FR] Ability to turn on printer without using GCode

### ISSUE THREAD

**Issue by lightmaster** [jneilliii/OctoPrint-TasmotaMQTT#54]
My printer is connected to a Wifi plug that turn on and off the power. I've recently started using OctoDash and I'm trying to figure out a way to get OctoDash to turn on my printer automatically. Obviously Octoprint prevents you from sending gcode when the printer is off, even gcode that is intercepted by this plugin. Would it be possible to use a System Command or some other method besides gcode to get this plugin to turn the switch on and off?

**Comment by jneilliii** [comment]
Yes, there is an API that you can use with a curl command, you just have to have a user/app API key in the command that you configure. You can use the same one you use for OctoDash. I just documented them [here](https://github.com/jneilliii/OctoPrint-TasmotaMQTT/wiki/API) for you, but the one you're specifically after for power on from a local OctoDash install is below.

```
curl -s -H "Content-Type: application/json" -H "X-Api-Key: YOUR_API_KEY" -X POST -d '{ "command":"turnOn", "topic":"<topic of tasmota device in settings>", "relayN":"<relay number of tasmota device in settings>" }' http://localhost:5000/api/plugin/tasmota_mqtt
```

**Comment by lightmaster** [comment]
This works great, except that Octodash currently only supports PSU Control. Gonna throw up a feature request with Octodash to add direct support for this plugin or just being able to send curl/system commands directly.

**Comment by jneilliii** [comment]
Oh right, you don't get any buttons when the printer isn't connected do you? I forgot about that with OctoDash. I know there's been some development being done actively on OctoDash, so might want to definitely check over there. There may even already be a feature request for it or one of my other Power IoT plugins.

**Comment by lightmaster** [comment]
No buttons, but it can send a turn on signal to PSU Control when you touch the sleeping screen. Hopefully can get native support for a Tasmota plugin, but if not, can get PSU Control to send a curl request to this plugin to turn on the printer. Just trying to get that dev to fix his System Command part. It removes the quotes from a system command and causes curl to hang until you kill it.

Definitely a pretty janky way to go about it, but better than nothing until something better is added.

**Comment by jneilliii** [comment]
I just dug through the source code and Uncharted has added TPLink plugin support to what's active now, so it wouldn't be that difficult to copy all those references/files and adapt for Tasmota I wouldn't think. It's just an additional setting for index.

**Comment by jneilliii** [comment]
So I've been able to adapt my non-MQTT version of the Tasmota plugin to work with OctoDash and submitted a [PR](https://github.com/UnchartedBull/OctoDash/pull/1581). I'll look into adding tasmota_mqtt support tomorrow.

**Comment by lightmaster** [comment]
Sweet. Looking forward to it.

**Comment by jneilliii** [comment]
@UnchartedBull merged my changes so this ability will be available in the next official release of OctoDash.
