### ISSUE TITLE
My plug with tasmota won´t work with this plugin

### ISSUE THREAD

**Issue by meier81** [jneilliii/OctoPrint-TasmotaMQTT#65]
Hello,

i have a problem. I own a plug Sonoff S20 and it´s flashed with the actual tasmota firmware. My MQTT-Config:

<img width="258" alt="MQTT" src="https://user-images.githubusercontent.com/40598096/204649548-b1cd9a2b-7716-4e07-9030-ecc1bb40c233.png">

<img width="374" alt="Info" src="https://user-images.githubusercontent.com/40598096/204651067-51b91baf-916c-4461-bc10-e0cdca3eafef.png">

Now i installed the "MQTT"-Plugin and the "OctoPrint-TasmotaMQTT"-Plugin. The "MQTT"-Plugin i have only added the Host IP-Adress, the other parameters are default.

In the "OctoPrint-TasmotaMQTT"-Plugin i've tried all the settings, none of them work here, neither for switching nor for feedback.

Can anyone help me what i have to configure?

Greetings and thanks, Markus

**Comment by jneilliii** [comment]
Can you share screenshots of the plugin's settings please?

**Comment by meier81** [comment]
Yes, here the plugin settings:

<img width="329" alt="Plugin" src="https://user-images.githubusercontent.com/40598096/204772714-307cde10-a967-4e90-89ef-aa2cd0cf0d71.png">

**Comment by meier81** [comment]
that was the first what i testet but it didn´t work.

<img width="427" alt="settings" src="https://user-images.githubusercontent.com/40598096/204883398-5846a872-3ff9-43ac-a9b3-1f465fd07172.png">

**Comment by meier81** [comment]
We can close the thread here, I have now used the octoprint-tasmota plugin, which works perfectly so far.

Greetings and thanks

Markus

**Comment by jneilliii** [comment]
was going to get you to try to enable debug logging and see if anything shows in octoprint.log or plugin_tasmotamqtt_debug.log after restarting OctoPrint. my other plugin is a little more developed in its feature set so probably is a little more stable.
