### ISSUE TITLE
not sending MQTT requests for new devices

### ISSUE THREAD

**Issue by TechnoSwiss** [jneilliii/OctoPrint-TasmotaMQTT#66]
I'm trying to setup some new Tasmota plugs in Octoprint 1.9.3 with OctoPrint-TasmotaMQTT 0.3.9, existing devices are working fine, but when I add new devices while the logfile says that messages are being sent, I'm not seeing any MQTT messages, and I'm just getting a spinning icon (since the cmd/POWER command isn't actually getting published, and therefore not getting a response)

![image](https://github.com/jneilliii/OctoPrint-TasmotaMQTT/assets/3485582/b9d2b25b-a65f-4987-bf83-faeb2b8d215c)

On another system I've subscribed to the topics tasmota/#, and just in case stat/#, tele/#, and cmnd/#

When I restart the octoprint server I see the following messages only:

`tasmota/plg-ender3/cmnd/POWER (null)`
`tasmota/plg-ender3/stat/RESULT {"POWER":"OFF"}`
`tasmota/plg-ender3/stat/POWER OFF`

Octoprint debug log shows

`2024-04-12 22:56:13,160 - octoprint.plugins.mqtt - DEBUG - Sent message: tasmota/plg-ender3/cmnd/POWER - , retain=True`
`2024-04-12 22:56:13,163 - octoprint.plugins.mqtt - DEBUG - Sent message: tasmota/plg-prusaxl/cmnd/POWER - , retain=True`

TasmotaMQTT log shows

`[2024-04-12 22:55:48,696] DEBUG: tasmota/plg-ender3/stat/POWER`
`[2024-04-12 22:55:48,708] DEBUG: tasmota/plg-prusaxl/stat/POWER`
`[2024-04-12 22:55:48,742] DEBUG: abortTimeout: 30`
`[2024-04-12 22:55:48,743] DEBUG: powerOffWhenIdle: True`
`[2024-04-12 22:55:48,755] DEBUG: idleTimeout: 15`
`[2024-04-12 22:55:48,757] DEBUG: idleIgnoreCommands: M105`
`[2024-04-12 22:55:48,764] DEBUG: idleTimeoutWaitTemp: 50`
`[2024-04-12 22:55:48,775] DEBUG: Starting idle timer due to startup`
`[2024-04-12 22:56:13,157] DEBUG: checking status of plg-ender3 relay `
`[2024-04-12 22:56:13,160] DEBUG: checking status of plg-prusaxl relay `
`[2024-04-12 22:56:13,258] DEBUG: Received message for tasmota/plg-ender3/stat/POWER: b'OFF'``

I've tried uninstalling and removing all data for the plugin, and reinstalling, and still I can only get the original device I set up over a year ago plg-ender3 to work, but not the new device plg-prusaxl. I can use mosquitto on the command line to publish 'tasmota/plg-prusaxl/cmnd/POWER (null)' and get the correct responses back,

**Comment by jneilliii** [comment]
double-check on the tasomta side that your full topic matches what's configured in the plugin's settings.

**Comment by TechnoSwiss** [comment]
![image](https://github.com/jneilliii/OctoPrint-TasmotaMQTT/assets/3485582/4496f713-42ae-43f0-8f66-829e5b825c68)

I have verified that, but even if it was different, I've subed to tasmota/# so if TasmotaMQTT was sending a pub even if I'd messed up anything after tasmota/ I should still see it come across. I think?

Is there some way I can test that it's sending, or getting an error, maybe a away to have TasmotaMQTT send a request from the command line?

**Comment by jneilliii** [comment]
with debug logging enabled in the plugin's settings and restarting OctoPrint it should show when the commands are being sent. You could enable gcode trigger and then send the gcode commands from the terminal tab. One thing that would help would be seeing the communication on the tasmota console. Only other thing I can think of is if SetOption26 is enabled but you don't have the relay number defined.

**Comment by TechnoSwiss** [comment]
well... facepalm, they were getting dropped on the MQTT server side.
