### ISSUE TITLE
Doesn't gracefully disconnect before GCODE off

### ISSUE THREAD

**Issue by mpfl** [jneilliii/OctoPrint-TasmotaMQTT#7]
I've started putting the M81 in my finishing GCODE for my prints and it works a treat. Unfortunately, despite being told to auto disconnect before turning off the printer, it doesn't.

I think this might be interacting poorly with the Pushover plugin, which I've configured to send me a notification when a print job is complete.

**Comment by jneilliii** [comment]
I'll need to check, I may not actually be checking those options on gcode processing. I'll review this weekend.

**Comment by mpfl** [comment]
It's also not paying attention to the GCODE off delay, it seems (I was actually present when the job finished). I'm not sure what a value of 600 should be - either 10 seconds or 10 minutes - but the printer turned off immediately once the job finished.

**Comment by jneilliii** [comment]
Thanks, I've confirmed the first bug. The second issue you mentioned should work, but I've not personally tested.  Can you add a screenshot of your settings of your relay for me?

**Comment by jneilliii** [comment]
New version 0.2.3 released that fixes both these issues. FYI, all timing settings are in seconds.
