### ISSUE TITLE
Plugin does not check whether printer is currently printing when powering off after gcode delay

### ISSUE THREAD

**Issue by mpfl** [jneilliii/OctoPrint-TasmotaMQTT#9]
As per the title.

I have set my printer to turn off after a period of time after a print is complete so that the cool end fan keeps running until the hot end has cooled down a bit. The most recent version of the plugin has made this very easy.

Unfortunately, I forgot about this behaviour just now and launched right into a new print job as soon as one had completed. The plugin then dutifully turned off the printer after the configured delay, even though the printer was still printing.

I suggest that the plugin check whether the printer is currently printing before turning it off.

**Comment by jneilliii** [comment]
You're right, the gcode option does bypass the "warn" settings because when I was thinking of the automation process I was thinking if you didn't have the ui loaded it would interfere. The isPrinting warning does make sense however.
